# Copyright (c) 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
---
# Default values for ditto.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  jwtOnly: false
  basicAuthUsers:
    ditto:
      user: ditto
      password: ditto
  logging:
    customConfigFile:
      enabled: true

## ----------------------------------------------------------------------------
## policies configuration
## ref: https://www.eclipse.dev/ditto/architecture-services-policies.html
policies:
  resources:
    cpu: 0.2
    memoryMi: 512
  jvm:
    activeProcessorCount: 2
    heapRamPercentage: 50
  config:
    persistence:
      events:
        historicalHeadersToPersist:
        - "ditto-originator"
        - "ditto-origin"
        - "correlation-id"
    entityCreation:
      grants:
        - namespaces:
          - "org.eclipse.ditto.room"
          authSubjects:
          - "connection:some"

## ----------------------------------------------------------------------------
## things configuration
## ref: https://www.eclipse.dev/ditto/architecture-services-things.html
things:
  resources:
    cpu: 0.2
    memoryMi: 512
  jvm:
    activeProcessorCount: 2
    heapRamPercentage: 50
  config:
    persistence:
      events:
        historicalHeadersToPersist:
          - "ditto-originator"
          - "ditto-origin"
          - "correlation-id"
    entityCreation:
      grants:
        - namespaces:
          - "org.eclipse.ditto.room"
          authSubjects:
          - "connection:some"

## ----------------------------------------------------------------------------
## things-search configuration
## ref: https://www.eclipse.dev/ditto/architecture-services-things-search.html
thingsSearch:
  resources:
    cpu: 0.2
    memoryMi: 512
  jvm:
    activeProcessorCount: 2
    heapRamPercentage: 50

## ----------------------------------------------------------------------------
## connectivity configuration
## ref: https://www.eclipse.dev/ditto/architecture-services-connectivity.html
connectivity:
  resources:
    cpu: 0.2
    memoryMi: 768
  jvm:
    activeProcessorCount: 2
    heapRamPercentage: 55

## ----------------------------------------------------------------------------
## gateway configuration
## ref: https://www.eclipse.dev/ditto/architecture-services-gateway.html
gateway:
  resources:
    cpu: 0.2
    memoryMi: 512
  jvm:
    activeProcessorCount: 2
    heapRamPercentage: 50
  config:
    authentication:
      enablePreAuthentication: true
      oauth:
        openidConnectIssuers:
         example:
           issuer: "example.com"
           authSubjects:
           - "{{ jwt:sub }}"
           - "{{ jwt:groups }}"
      devops:
        ## this controls whether /devops resource is secured or not
        secured: true
        authMethod: "basic"
        oauth:
          # configure the amount of clock skew in seconds to tolerate when verifying the local time against the exp and nbf claims
          allowedClockSkew: 20s
          openidConnectIssuers:
           example-ops:
             issuer: "example.com"
             authSubjects:
             - "{{ jwt:sub }}"
             - "{{ jwt:groups }}"
        oauthSubjects:
        - "example-ops:devops-admin"
        ## this controls whether /status resource is secured or not
        statusSecured: true
        statusAuthMethod: "basic"
        # array of strings for subjects authorized to use "/status" API
        statusOauthSubjects:
        - "example-ops:devops-admin"

## ----------------------------------------------------------------------------
## nginx configuration
nginx:
  resources:
    cpu: 0.1
    memoryMi: 64
  initContainers:
    waitForGateway:
      enabled: false

## ----------------------------------------------------------------------------
## mongodb dependency chart configuration
mongodb:
  enabled: false
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 256Mi
  readinessProbe:
    enabled: false
  livenessProbe:
    enabled: false
  auth:
    enabled: false
  persistence:
    enabled: true
